In [288]:
import pandas as pd
import numpy as np

In [289]:
df=pd.read_excel('Desktop/emplo_1.xlsx',header=1)

In [290]:
df = df.iloc[2: , :]

In [291]:
df.isnull().sum()

,at risk,Name,Career Week end date,Days since graduation,Cohort Name,Outcome Category,Outcome Status,Track,Format,Campus,CV,Linkedin,Portfolio,Job ready pct,Soft skills score,Soft skills pct,Assessment score,Lab score,Final project grade,Final project pct
2,NaN,Valentine Parker,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.714286,0.742857,96.75,4.78,2.860,0.94952
3,ðŸš©,Gregoria Veum III,2022-06-23,71.0,Cohort1,Excluded,Not Eligible,WD,FT,RMT,0.0,0.0,0.00,0.000000,1.000000,0.200000,48.71,3.90,1.790,0.59428
4,NaN,Isai Turcotte DVM,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.285714,0.657143,63.25,4.33,2.360,0.78352
5,NaN,Alex Mueller,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.571429,0.714286,99.35,4.50,1.860,0.61752
6,NaN,Coy Kuphal,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.000000,0.400000,45.66,4.00,2.290,0.76028
7,NaN,Janis Bayer,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.000000,0.600000,95.24,4.87,2.860,0.94952
8,NaN,Mr. Emelia Graham,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,4.000000,0.800000,85.97,4.42,2.860,0.94952
9,NaN,Drake Hills,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.857143,0.571429,88.79,4.38,2.860,0.94952
10,NaN,Kirk Mosciski,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,1.571429,0.314286,81.64,4.11,2.210,0.73372
11,NaN,Verda Osinski,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.142857,0.428571,100,4.50,1.790,0.59428
12,NaN,Lucius McCullough,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.142857,0.428571,74.66,3.84,2.290,0.76028
13,NaN,Lilliana Herman,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,1.714286,0.342857,54.95,3.84,2.210,0.73372
14,NaN,Lavina Schaefer,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.428571,0.485714,91.99,4.26,2.360,0.78352
15,ðŸš©,Ewell Hammes,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,0.00,0.666667,1.000000,0.200000,23.44,3.20,2.000,0.66400
16,ðŸš©,Kassandra Bernier,2022-06-23,71.0,Cohort1,Employed,Hired In Field,WD,FT,RMT,1.0,1.0,0.00,0.666667,1.000000,0.200000,,3.42,1.710,0.56772
17,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Clemens Fisher,2022-06-24,70.0,Cohort2,Excluded,Back To Job,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,98.86,NaN,2.430,0.80676
19,NaN,Dennis Kilback,2022-06-24,70.0,Cohort2,Employed,Hired In Field,NaN,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,76.14,NaN,1.710,0.56772
20,NaN,Nicholas Miller,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,98.86,NaN,2.430,0.80676
21,NaN,Claude Kautzer DDS,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,96.97,NaN,1.710,0.56772
22,NaN,Nia Brown,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,86.36,NaN,1.930,0.64076
23,NaN,Kirk Carroll,2022-06-24,70.0,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,98.86,NaN,2.790,0.92628
24,NaN,Libbie Sauer,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,54.38,NaN,1.860,0.61752
25,NaN,Emmitt Jaskolski,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,90.75,NaN,1.930,0.64076
26,NaN,Susanna Kulas,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,100,NaN,2.000,0.66400
27,NaN,Torrey Lueilwitz,2022-06-24,70.0,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,100,NaN,2.070,0.68724
28,NaN,Lura Hammes,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,87.88,NaN,1.790,0.59428
29,NaN,Mattie Reinger,2022-06-24,70.0,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,55.68,NaN,1.930,0.64076
30,NaN,Luna Hoeger,2022-06-24,70.0,Cohort2,Excluded,Entrepreneur,NaN,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,90.48,NaN,1.930,0.64076
31,NaN,Kelton Spinka,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,95.45,NaN,2.210,0.73372
32,NaN,Leonardo Mueller,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,71.1,NaN,1.860,0.61752
33,NaN,Miss Jayda Okuneva,2022-06-24,70.0,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,100,NaN,2.000,0.66400
34,NaN,Alexandrine Pouros,2022-06-24,70.0,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,96.59,NaN,2.000,0.66400
35,NaN,Carleton Bayer,2022-06-24,70.0,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,95.29,NaN,2.290,0.76028
36,NaN,Mrs. Delaney Koch,2022-06-24,70.0,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,93.72,NaN,1.930,0.64076
37,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,Faye Rowe,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,1.0,0.00,0.333333,3.875000,0.775000,73.43,3.87,1.875,0.62250
39,NaN,Mandy Toy,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,3.875000,0.775000,100,5.00,2.375,0.78850
40,NaN,Ursula Quigley,2022-06-27,67.0,Cohort3,Excluded,Not Eligible,WD,FT,MAD,1.0,1.0,0.00,0.666667,4.000000,0.800000,95.25,4.30,2.000,0.66400
41,NaN,Alfonso Herman,2022-06-27,67.0,Cohort3,Employed,Ironhack Employee,WD,FT,MAD,0.0,1.0,0.01,0.336667,4.750000,0.950000,98.86,4.74,1.875,0.62250
42,NaN,Orin Smith,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.625000,0.925000,61.36,4.57,2.375,0.78850
43,NaN,Felicia Hettinger,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.333333,0.866667,96.36,4.48,2.125,0.70550
44,NaN,Raphael Koss DVM,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.500000,0.900000,98.18,4.52,1.875,0.62250
45,NaN,Cristina Kreiger,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,86.36,4.48,2.375,0.78850
46,NaN,Marilou Torp,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.166667,0.833333,62.73,2.48,1.625,0.53950
47,NaN,Lorena Reichel,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,98.18,4.65,2.125,0.70550
48,NaN,Elvie Simonis,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,74.55,4.27,2.375,0.78850
49,NaN,Tianna Langosh,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,1.00,0.333333,3.833333,0.766667,52.29,3.14,1.625,0.53950
50,NaN,Dr. Estelle Homenick,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,54.61,3.52,2.375,0.78850
51,NaN,Uriel Harvey,2022-06-27,67.0,Cohort3,Excluded,Not Graduated In Career Services,WD,FT,MAD,1.0,1.0,1.00,1.000000,5.000000,1.000000,90.91,4.61,1.875,0.62250
52,NaN,Marilie Spencer DDS,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,83.84,4.43,2.125,0.70550
53,NaN,Nettie O'Keefe,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,72.12,3.52,2.125,0.70550
54,NaN,Antone Denesik,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.500000,0.900000,97.98,4.57,1.875,0.62250
55,NaN,Roscoe Gaylord,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,5.000000,1.000000,95.76,4.83,1.875,0.62250
56,NaN,Shanelle HarÂªann II,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,55.45,3.68,2.375,0.78850
57,NaN,Kelton Runolfsdottir,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.333333,0.666667,80.43,3.65,2.000,0.66400
58,NaN,Eileen Krajcik,2022-06-27,67.0,Cohort3,Excluded,Back To Job,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.000000,0.600000,92.52,3.48,2.000,0.66400
59,NaN,Lempi Marvin,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.500000,0.700000,16.02,2.45,1.625,0.53950
60,NaN,Mr. Estella Kulas,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.250000,0.850000,96.36,4.13,2.125,0.70550

In [292]:
df=df.reset_index(drop=True)

In [293]:
df=df.dropna(how='all')

In [294]:
df=df.drop_duplicates(keep='first')

In [295]:
df['Days since graduation']=df['Days since graduation'].astype(int)

In [296]:
df.loc[df['at risk'].isnull(),'at risk']='No'
df.loc[df['at risk']!='No','at risk']='Yes'

In [297]:
df

,at risk,Name,Career Week end date,Days since graduation,Cohort Name,Outcome Category,Outcome Status,Track,Format,Campus,CV,Linkedin,Portfolio,Job ready pct,Soft skills score,Soft skills pct,Assessment score,Lab score,Final project grade,Final project pct
0,No,Valentine Parker,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.714286,0.742857,96.75,4.78,2.860,0.94952
1,Yes,Gregoria Veum III,2022-06-23,71,Cohort1,Excluded,Not Eligible,WD,FT,RMT,0.0,0.0,0.00,0.000000,1.000000,0.200000,48.71,3.90,1.790,0.59428
2,No,Isai Turcotte DVM,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.285714,0.657143,63.25,4.33,2.360,0.78352
3,No,Alex Mueller,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.571429,0.714286,99.35,4.50,1.860,0.61752
4,No,Coy Kuphal,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.000000,0.400000,45.66,4.00,2.290,0.76028
5,No,Janis Bayer,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.000000,0.600000,95.24,4.87,2.860,0.94952
6,No,Mr. Emelia Graham,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,4.000000,0.800000,85.97,4.42,2.860,0.94952
7,No,Drake Hills,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.857143,0.571429,88.79,4.38,2.860,0.94952
8,No,Kirk Mosciski,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,1.571429,0.314286,81.64,4.11,2.210,0.73372
9,No,Verda Osinski,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.142857,0.428571,100,4.50,1.790,0.59428
10,No,Lucius McCullough,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.142857,0.428571,74.66,3.84,2.290,0.76028
11,No,Lilliana Herman,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,1.714286,0.342857,54.95,3.84,2.210,0.73372
12,No,Lavina Schaefer,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.428571,0.485714,91.99,4.26,2.360,0.78352
13,Yes,Ewell Hammes,2022-06-23,71,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,0.00,0.666667,1.000000,0.200000,23.44,3.20,2.000,0.66400
14,Yes,Kassandra Bernier,2022-06-23,71,Cohort1,Employed,Hired In Field,WD,FT,RMT,1.0,1.0,0.00,0.666667,1.000000,0.200000,,3.42,1.710,0.56772
16,No,Clemens Fisher,2022-06-24,70,Cohort2,Excluded,Back To Job,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,98.86,NaN,2.430,0.80676
17,No,Dennis Kilback,2022-06-24,70,Cohort2,Employed,Hired In Field,NaN,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,76.14,NaN,1.710,0.56772
18,No,Nicholas Miller,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,98.86,NaN,2.430,0.80676
19,No,Claude Kautzer DDS,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,96.97,NaN,1.710,0.56772
20,No,Nia Brown,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,86.36,NaN,1.930,0.64076
21,No,Kirk Carroll,2022-06-24,70,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,98.86,NaN,2.790,0.92628
22,No,Libbie Sauer,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,54.38,NaN,1.860,0.61752
23,No,Emmitt Jaskolski,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,90.75,NaN,1.930,0.64076
24,No,Susanna Kulas,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,100,NaN,2.000,0.66400
25,No,Torrey Lueilwitz,2022-06-24,70,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,100,NaN,2.070,0.68724
26,No,Lura Hammes,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,87.88,NaN,1.790,0.59428
27,No,Mattie Reinger,2022-06-24,70,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,55.68,NaN,1.930,0.64076
28,No,Luna Hoeger,2022-06-24,70,Cohort2,Excluded,Entrepreneur,NaN,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,90.48,NaN,1.930,0.64076
29,No,Kelton Spinka,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,95.45,NaN,2.210,0.73372
30,No,Leonardo Mueller,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,71.1,NaN,1.860,0.61752
31,No,Miss Jayda Okuneva,2022-06-24,70,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,100,NaN,2.000,0.66400
32,No,Alexandrine Pouros,2022-06-24,70,Cohort2,Searching,Searching,NaN,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,96.59,NaN,2.000,0.66400
33,No,Carleton Bayer,2022-06-24,70,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,95.29,NaN,2.290,0.76028
34,No,Mrs. Delaney Koch,2022-06-24,70,Cohort2,Employed,Hired In Field,NaN,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,93.72,NaN,1.930,0.64076
36,No,Faye Rowe,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,0.0,1.0,0.00,0.333333,3.875000,0.775000,73.43,3.87,1.875,0.62250
37,No,Mandy Toy,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,3.875000,0.775000,100,5.00,2.375,0.78850
38,No,Ursula Quigley,2022-06-27,67,Cohort3,Excluded,Not Eligible,WD,FT,MAD,1.0,1.0,0.00,0.666667,4.000000,0.800000,95.25,4.30,2.000,0.66400
39,No,Alfonso Herman,2022-06-27,67,Cohort3,Employed,Ironhack Employee,WD,FT,MAD,0.0,1.0,0.01,0.336667,4.750000,0.950000,98.86,4.74,1.875,0.62250
40,No,Orin Smith,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.625000,0.925000,61.36,4.57,2.375,0.78850
41,No,Felicia Hettinger,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.333333,0.866667,96.36,4.48,2.125,0.70550
42,No,Raphael Koss DVM,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.500000,0.900000,98.18,4.52,1.875,0.62250
43,No,Cristina Kreiger,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,86.36,4.48,2.375,0.78850
44,No,Marilou Torp,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.166667,0.833333,62.73,2.48,1.625,0.53950
45,No,Lorena Reichel,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,98.18,4.65,2.125,0.70550
46,No,Elvie Simonis,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,74.55,4.27,2.375,0.78850
47,No,Tianna Langosh,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,1.00,0.333333,3.833333,0.766667,52.29,3.14,1.625,0.53950
48,No,Dr. Estelle Homenick,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,54.61,3.52,2.375,0.78850
49,No,Uriel Harvey,2022-06-27,67,Cohort3,Excluded,Not Graduated In Career Services,WD,FT,MAD,1.0,1.0,1.00,1.000000,5.000000,1.000000,90.91,4.61,1.875,0.62250
50,No,Marilie Spencer DDS,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,83.84,4.43,2.125,0.70550
51,No,Nettie O'Keefe,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,72.12,3.52,2.125,0.70550
52,No,Antone Denesik,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.500000,0.900000,97.98,4.57,1.875,0.62250
53,No,Roscoe Gaylord,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,5.000000,1.000000,95.76,4.83,1.875,0.62250
54,No,Shanelle HarÂªann II,2022-06-27,67,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,55.45,3.68,2.375,0.78850
55,No,Kelton Runolfsdottir,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.333333,0.666667,80.43,3.65,2.000,0.66400
56,No,Eileen Krajcik,2022-06-27,67,Cohort3,Excluded,Back To Job,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.000000,0.600000,92.52,3.48,2.000,0.66400
57,No,Lempi Marvin,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.500000,0.700000,16.02,2.45,1.625,0.53950
58,No,Mr. Estella Kulas,2022-06-27,67,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.250000,0.850000,96.36,4.13,2.125,0.70550

In [298]:
df['Career Week end date'].unique()

array(['2022-06-23T00:00:00.000000000', '2022-06-24T00:00:00.000000000',
       '2022-06-27T00:00:00.000000000'], dtype='datetime64[ns]')

In [299]:
df['Days since graduation'].unique()

array([71, 70, 67])

In [300]:
df['Outcome Category'].unique()

array(['Searching', 'Excluded', 'Employed'], dtype=object)

In [301]:
df['Outcome Status'].unique()

array(['Searching', 'Not Eligible', 'Hired In Field', 'Back To Job',
       'Entrepreneur', 'Ironhack Employee',
       'Not Graduated In Career Services'], dtype=object)

In [302]:
df['Track'].unique()
df.loc[df['Track'].isnull(),'Track']='Other'
df.columns

Index(['at risk', 'Name', 'Career Week end date', 'Days since graduation',
       'Cohort Name', 'Outcome Category', 'Outcome Status', 'Track', 'Format',
       'Campus', 'CV', 'Linkedin', 'Portfolio', 'Job ready pct',
       'Soft skills score', 'Soft skills pct', 'Assessment score', 'Lab score',
       'Final project grade', 'Final project pct'],
      dtype='object')

In [303]:
for col in df.columns:
    df.loc[df[col]==" ",col]=np.nan
df

,at risk,Name,Career Week end date,Days since graduation,Cohort Name,Outcome Category,Outcome Status,Track,Format,Campus,CV,Linkedin,Portfolio,Job ready pct,Soft skills score,Soft skills pct,Assessment score,Lab score,Final project grade,Final project pct
0,No,Valentine Parker,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.714286,0.742857,96.75,4.78,2.860,0.94952
1,Yes,Gregoria Veum III,2022-06-23,71.0,Cohort1,Excluded,Not Eligible,WD,FT,RMT,0.0,0.0,0.00,0.000000,1.000000,0.200000,48.71,3.90,1.790,0.59428
2,No,Isai Turcotte DVM,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.285714,0.657143,63.25,4.33,2.360,0.78352
3,No,Alex Mueller,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.571429,0.714286,99.35,4.50,1.860,0.61752
4,No,Coy Kuphal,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.000000,0.400000,45.66,4.00,2.290,0.76028
5,No,Janis Bayer,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,3.000000,0.600000,95.24,4.87,2.860,0.94952
6,No,Mr. Emelia Graham,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,4.000000,0.800000,85.97,4.42,2.860,0.94952
7,No,Drake Hills,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.857143,0.571429,88.79,4.38,2.860,0.94952
8,No,Kirk Mosciski,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,1.571429,0.314286,81.64,4.11,2.210,0.73372
9,No,Verda Osinski,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.142857,0.428571,100,4.50,1.790,0.59428
10,No,Lucius McCullough,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.142857,0.428571,74.66,3.84,2.290,0.76028
11,No,Lilliana Herman,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,1.714286,0.342857,54.95,3.84,2.210,0.73372
12,No,Lavina Schaefer,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,1.000000,2.428571,0.485714,91.99,4.26,2.360,0.78352
13,Yes,Ewell Hammes,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,0.00,0.666667,1.000000,0.200000,23.44,3.20,2.000,0.66400
14,Yes,Kassandra Bernier,2022-06-23,71.0,Cohort1,Employed,Hired In Field,WD,FT,RMT,1.0,1.0,0.00,0.666667,1.000000,0.200000,NaN,3.42,1.710,0.56772
16,No,Clemens Fisher,2022-06-24,70.0,Cohort2,Excluded,Back To Job,Other,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,98.86,NaN,2.430,0.80676
17,No,Dennis Kilback,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,76.14,NaN,1.710,0.56772
18,No,Nicholas Miller,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,98.86,NaN,2.430,0.80676
19,No,Claude Kautzer DDS,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,96.97,NaN,1.710,0.56772
20,No,Nia Brown,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,86.36,NaN,1.930,0.64076
21,No,Kirk Carroll,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,98.86,NaN,2.790,0.92628
22,No,Libbie Sauer,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,54.38,NaN,1.860,0.61752
23,No,Emmitt Jaskolski,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,90.75,NaN,1.930,0.64076
24,No,Susanna Kulas,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,100,NaN,2.000,0.66400
25,No,Torrey Lueilwitz,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,100,NaN,2.070,0.68724
26,No,Lura Hammes,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,87.88,NaN,1.790,0.59428
27,No,Mattie Reinger,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,55.68,NaN,1.930,0.64076
28,No,Luna Hoeger,2022-06-24,70.0,Cohort2,Excluded,Entrepreneur,Other,FT,LIS,0.0,0.0,0.00,0.000000,NaN,NaN,90.48,NaN,1.930,0.64076
29,No,Kelton Spinka,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,95.45,NaN,2.210,0.73372
30,No,Leonardo Mueller,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,71.1,NaN,1.860,0.61752
31,No,Miss Jayda Okuneva,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,100,NaN,2.000,0.66400
32,No,Alexandrine Pouros,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,0.666667,NaN,NaN,96.59,NaN,2.000,0.66400
33,No,Carleton Bayer,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,95.29,NaN,2.290,0.76028
34,No,Mrs. Delaney Koch,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,1.00,1.000000,NaN,NaN,93.72,NaN,1.930,0.64076
36,No,Faye Rowe,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,1.0,0.00,0.333333,3.875000,0.775000,73.43,3.87,1.875,0.62250
37,No,Mandy Toy,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,3.875000,0.775000,100,5.00,2.375,0.78850
38,No,Ursula Quigley,2022-06-27,67.0,Cohort3,Excluded,Not Eligible,WD,FT,MAD,1.0,1.0,0.00,0.666667,4.000000,0.800000,95.25,4.30,2.000,0.66400
39,No,Alfonso Herman,2022-06-27,67.0,Cohort3,Employed,Ironhack Employee,WD,FT,MAD,0.0,1.0,0.01,0.336667,4.750000,0.950000,98.86,4.74,1.875,0.62250
40,No,Orin Smith,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.625000,0.925000,61.36,4.57,2.375,0.78850
41,No,Felicia Hettinger,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.333333,0.866667,96.36,4.48,2.125,0.70550
42,No,Raphael Koss DVM,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.500000,0.900000,98.18,4.52,1.875,0.62250
43,No,Cristina Kreiger,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,86.36,4.48,2.375,0.78850
44,No,Marilou Torp,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.166667,0.833333,62.73,2.48,1.625,0.53950
45,No,Lorena Reichel,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,98.18,4.65,2.125,0.70550
46,No,Elvie Simonis,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,74.55,4.27,2.375,0.78850
47,No,Tianna Langosh,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,1.00,0.333333,3.833333,0.766667,52.29,3.14,1.625,0.53950
48,No,Dr. Estelle Homenick,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,54.61,3.52,2.375,0.78850
49,No,Uriel Harvey,2022-06-27,67.0,Cohort3,Excluded,Not Graduated In Career Services,WD,FT,MAD,1.0,1.0,1.00,1.000000,5.000000,1.000000,90.91,4.61,1.875,0.62250
50,No,Marilie Spencer DDS,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,83.84,4.43,2.125,0.70550
51,No,Nettie O'Keefe,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.666667,0.933333,72.12,3.52,2.125,0.70550
52,No,Antone Denesik,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.500000,0.900000,97.98,4.57,1.875,0.62250
53,No,Roscoe Gaylord,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0.000000,5.000000,1.000000,95.76,4.83,1.875,0.62250
54,No,Shanelle HarÂªann II,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,1.000000,4.666667,0.933333,55.45,3.68,2.375,0.78850
55,No,Kelton Runolfsdottir,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.333333,0.666667,80.43,3.65,2.000,0.66400
56,No,Eileen Krajcik,2022-06-27,67.0,Cohort3,Excluded,Back To Job,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.000000,0.600000,92.52,3.48,2.000,0.66400
57,No,Lempi Marvin,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,3.500000,0.700000,16.02,2.45,1.625,0.53950
58,No,Mr. Estella Kulas,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0.000000,4.250000,0.850000,96.36,4.13,2.125,0.70550

In [304]:
def clean_df(df,cohort,scores):
    for score in scores:
        df.loc[(df['Cohort Name']==cohort)&(df[score].isna()),score]=df[df['Cohort Name']==cohort][score].mean()
    return df

In [305]:
df.isnull().sum()

at risk                   0
Name                      0
Career Week end date      0
Days since graduation     0
Cohort Name               0
Outcome Category          0
Outcome Status            0
Track                     0
Format                    0
Campus                    0
CV                        0
Linkedin                  0
Portfolio                 0
Job ready pct             0
Soft skills score        19
Soft skills pct          19
Assessment score          1
Lab score                19
Final project grade       0
Final project pct         0
dtype: int64

In [306]:
df=clean_df(df,'Cohort1',['Soft skills score','Soft skills pct','Assessment score','Lab score'])

In [307]:
df.isnull().sum()

at risk                   0
Name                      0
Career Week end date      0
Days since graduation     0
Cohort Name               0
Outcome Category          0
Outcome Status            0
Track                     0
Format                    0
Campus                    0
CV                        0
Linkedin                  0
Portfolio                 0
Job ready pct             0
Soft skills score        19
Soft skills pct          19
Assessment score          0
Lab score                19
Final project grade       0
Final project pct         0
dtype: int64

In [308]:
df['Final project pct']=df['Final project pct']*100
df['Final project pct']=df['Final project pct'].round(2)
df['Soft skills pct']=df['Soft skills pct']*100
df['Soft skills pct']=df['Soft skills pct'].round(2)
df['Job ready pct']=df['Job ready pct']*100
df['Job ready pct']=df['Job ready pct'].astype(int)

In [309]:
df

,at risk,Name,Career Week end date,Days since graduation,Cohort Name,Outcome Category,Outcome Status,Track,Format,Campus,CV,Linkedin,Portfolio,Job ready pct,Soft skills score,Soft skills pct,Assessment score,Lab score,Final project grade,Final project pct
0,No,Valentine Parker,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,3.714286,74.29,96.75,4.78,2.860,94.95
1,Yes,Gregoria Veum III,2022-06-23,71.0,Cohort1,Excluded,Not Eligible,WD,FT,RMT,0.0,0.0,0.00,0,1.000000,20.00,48.71,3.90,1.790,59.43
2,No,Isai Turcotte DVM,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,3.285714,65.71,63.25,4.33,2.360,78.35
3,No,Alex Mueller,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,3.571429,71.43,99.35,4.50,1.860,61.75
4,No,Coy Kuphal,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,2.000000,40.00,45.66,4.00,2.290,76.03
5,No,Janis Bayer,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,3.000000,60.00,95.24,4.87,2.860,94.95
6,No,Mr. Emelia Graham,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,4.000000,80.00,85.97,4.42,2.860,94.95
7,No,Drake Hills,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,2.857143,57.14,88.79,4.38,2.860,94.95
8,No,Kirk Mosciski,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,1.571429,31.43,81.64,4.11,2.210,73.37
9,No,Verda Osinski,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,2.142857,42.86,100,4.50,1.790,59.43
10,No,Lucius McCullough,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,2.142857,42.86,74.66,3.84,2.290,76.03
11,No,Lilliana Herman,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,1.714286,34.29,54.95,3.84,2.210,73.37
12,No,Lavina Schaefer,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,1.00,100,2.428571,48.57,91.99,4.26,2.360,78.35
13,Yes,Ewell Hammes,2022-06-23,71.0,Cohort1,Searching,Searching,WD,FT,RMT,1.0,1.0,0.00,66,1.000000,20.00,23.44,3.20,2.000,66.40
14,Yes,Kassandra Bernier,2022-06-23,71.0,Cohort1,Employed,Hired In Field,WD,FT,RMT,1.0,1.0,0.00,66,1.000000,20.00,75.028571,3.42,1.710,56.77
16,No,Clemens Fisher,2022-06-24,70.0,Cohort2,Excluded,Back To Job,Other,FT,LIS,1.0,1.0,0.00,66,NaN,NaN,98.86,NaN,2.430,80.68
17,No,Dennis Kilback,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,0.0,0.0,0.00,0,NaN,NaN,76.14,NaN,1.710,56.77
18,No,Nicholas Miller,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,66,NaN,NaN,98.86,NaN,2.430,80.68
19,No,Claude Kautzer DDS,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,1.00,100,NaN,NaN,96.97,NaN,1.710,56.77
20,No,Nia Brown,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,66,NaN,NaN,86.36,NaN,1.930,64.08
21,No,Kirk Carroll,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,1.00,100,NaN,NaN,98.86,NaN,2.790,92.63
22,No,Libbie Sauer,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,1.00,100,NaN,NaN,54.38,NaN,1.860,61.75
23,No,Emmitt Jaskolski,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,0.0,0.0,0.00,0,NaN,NaN,90.75,NaN,1.930,64.08
24,No,Susanna Kulas,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,1.00,100,NaN,NaN,100,NaN,2.000,66.40
25,No,Torrey Lueilwitz,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,0.00,66,NaN,NaN,100,NaN,2.070,68.72
26,No,Lura Hammes,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,66,NaN,NaN,87.88,NaN,1.790,59.43
27,No,Mattie Reinger,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,1.00,100,NaN,NaN,55.68,NaN,1.930,64.08
28,No,Luna Hoeger,2022-06-24,70.0,Cohort2,Excluded,Entrepreneur,Other,FT,LIS,0.0,0.0,0.00,0,NaN,NaN,90.48,NaN,1.930,64.08
29,No,Kelton Spinka,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,66,NaN,NaN,95.45,NaN,2.210,73.37
30,No,Leonardo Mueller,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,1.00,100,NaN,NaN,71.1,NaN,1.860,61.75
31,No,Miss Jayda Okuneva,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,0.00,66,NaN,NaN,100,NaN,2.000,66.40
32,No,Alexandrine Pouros,2022-06-24,70.0,Cohort2,Searching,Searching,Other,FT,LIS,1.0,1.0,0.00,66,NaN,NaN,96.59,NaN,2.000,66.40
33,No,Carleton Bayer,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,1.00,100,NaN,NaN,95.29,NaN,2.290,76.03
34,No,Mrs. Delaney Koch,2022-06-24,70.0,Cohort2,Employed,Hired In Field,Other,FT,LIS,1.0,1.0,1.00,100,NaN,NaN,93.72,NaN,1.930,64.08
36,No,Faye Rowe,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,1.0,0.00,33,3.875000,77.50,73.43,3.87,1.875,62.25
37,No,Mandy Toy,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,100,3.875000,77.50,100,5.00,2.375,78.85
38,No,Ursula Quigley,2022-06-27,67.0,Cohort3,Excluded,Not Eligible,WD,FT,MAD,1.0,1.0,0.00,66,4.000000,80.00,95.25,4.30,2.000,66.40
39,No,Alfonso Herman,2022-06-27,67.0,Cohort3,Employed,Ironhack Employee,WD,FT,MAD,0.0,1.0,0.01,33,4.750000,95.00,98.86,4.74,1.875,62.25
40,No,Orin Smith,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,100,4.625000,92.50,61.36,4.57,2.375,78.85
41,No,Felicia Hettinger,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0,4.333333,86.67,96.36,4.48,2.125,70.55
42,No,Raphael Koss DVM,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0,4.500000,90.00,98.18,4.52,1.875,62.25
43,No,Cristina Kreiger,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0,4.666667,93.33,86.36,4.48,2.375,78.85
44,No,Marilou Torp,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,100,4.166667,83.33,62.73,2.48,1.625,53.95
45,No,Lorena Reichel,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,100,4.666667,93.33,98.18,4.65,2.125,70.55
46,No,Elvie Simonis,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,100,4.666667,93.33,74.55,4.27,2.375,78.85
47,No,Tianna Langosh,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,1.00,33,3.833333,76.67,52.29,3.14,1.625,53.95
48,No,Dr. Estelle Homenick,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,1.0,1.0,1.00,100,4.666667,93.33,54.61,3.52,2.375,78.85
49,No,Uriel Harvey,2022-06-27,67.0,Cohort3,Excluded,Not Graduated In Career Services,WD,FT,MAD,1.0,1.0,1.00,100,5.000000,100.00,90.91,4.61,1.875,62.25
50,No,Marilie Spencer DDS,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0,4.666667,93.33,83.84,4.43,2.125,70.55
51,No,Nettie O'Keefe,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0,4.666667,93.33,72.12,3.52,2.125,70.55
52,No,Antone Denesik,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0,4.500000,90.00,97.98,4.57,1.875,62.25
53,No,Roscoe Gaylord,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,0.0,0.0,0.00,0,5.000000,100.00,95.76,4.83,1.875,62.25
54,No,Shanelle HarÂªann II,2022-06-27,67.0,Cohort3,Searching,Searching,WD,FT,MAD,1.0,1.0,1.00,100,4.666667,93.33,55.45,3.68,2.375,78.85
55,No,Kelton Runolfsdottir,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0,3.333333,66.67,80.43,3.65,2.000,66.40
56,No,Eileen Krajcik,2022-06-27,67.0,Cohort3,Excluded,Back To Job,WD,FT,MAD,0.0,0.0,0.00,0,3.000000,60.00,92.52,3.48,2.000,66.40
57,No,Lempi Marvin,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0,3.500000,70.00,16.02,2.45,1.625,53.95
58,No,Mr. Estella Kulas,2022-06-27,67.0,Cohort3,Employed,Hired In Field,WD,FT,MAD,0.0,0.0,0.00,0,4.250000,85.00,96.36,4.13,2.125,70.55

In [311]:
df.to_excel("Desktop/emplo_clean.xlsx")